# Generated by Django 5.2.7 on 2025-10-19 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(db_index=True, unique=True, verbose_name='사번')),
                ('amount', models.BigIntegerField(default=0, verbose_name='최종지급액')),
            ],
        ),
    ]
