# Generated by Django 5.2.7 on 2025-12-30 07:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_customuser_channel_customuser_part'),
        ('commission', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DepositOther',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, verbose_name='상품명')),
                ('amount', models.BigIntegerField(default=0, verbose_name='가입금액')),
                ('bond_no', models.CharField(blank=True, default='', max_length=100, verbose_name='채권번호')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='가입일')),
                ('memo', models.CharField(blank=True, default='', max_length=255, verbose_name='비고')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposit_others', to=settings.AUTH_USER_MODEL, verbose_name='사번')),
            ],
            options={
                'verbose_name': '기타채권',
                'verbose_name_plural': '기타채권',
                'db_table': 'deposit_others',
            },
        ),
        migrations.CreateModel(
            name='DepositSummary',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='deposit_summary', serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='사번')),
                ('final_payment', models.BigIntegerField(default=0, verbose_name='최종지급액')),
                ('refund_expected', models.BigIntegerField(default=0, verbose_name='환수예상')),
                ('pay_expected', models.BigIntegerField(default=0, verbose_name='지급예상')),
                ('ns_25_total', models.BigIntegerField(default=0, verbose_name='25회손보통산')),
                ('ls_25_total', models.BigIntegerField(default=0, verbose_name='25회생보통산')),
                ('surety_total', models.BigIntegerField(default=0, verbose_name='보증합계')),
                ('other_total', models.BigIntegerField(default=0, verbose_name='기타합계')),
                ('debt_total', models.BigIntegerField(default=0, verbose_name='채권합계')),
                ('required_debt', models.BigIntegerField(default=0, verbose_name='필요채권')),
                ('final_excess_amount', models.BigIntegerField(default=0, verbose_name='최종초과금액')),
                ('refund_ns', models.BigIntegerField(default=0, verbose_name='환수손보')),
                ('refund_ls', models.BigIntegerField(default=0, verbose_name='환수생보')),
                ('pay_ns', models.BigIntegerField(default=0, verbose_name='지급손보')),
                ('pay_ls', models.BigIntegerField(default=0, verbose_name='지급생보')),
                ('comm_3m', models.BigIntegerField(default=0, verbose_name='3개월총수수료')),
                ('comm_6m', models.BigIntegerField(default=0, verbose_name='6개월총수수료')),
                ('comm_9m', models.BigIntegerField(default=0, verbose_name='9개월총수수료')),
                ('comm_12m', models.BigIntegerField(default=0, verbose_name='12개월총수수료')),
                ('ns_18_total', models.BigIntegerField(default=0, verbose_name='18회손보통산')),
                ('ns_25_total_2', models.BigIntegerField(default=0, verbose_name='25회손보통산(2)')),
                ('ns_18_total_2', models.BigIntegerField(default=0, verbose_name='18손보통산')),
                ('ls_25_total_2', models.BigIntegerField(default=0, verbose_name='25회생보통산(2)')),
                ('ns_2_6_due', models.BigIntegerField(default=0, verbose_name='2-6회손보응당')),
                ('ns_2_13_due', models.BigIntegerField(default=0, verbose_name='2-13회손보응당')),
                ('ls_2_6_due', models.BigIntegerField(default=0, verbose_name='2-6회생보응당')),
                ('ls_2_13_due', models.BigIntegerField(default=0, verbose_name='2-13회생보응당')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '채권 요약',
                'verbose_name_plural': '채권 요약',
                'db_table': 'deposit_summary',
            },
        ),
        migrations.CreateModel(
            name='DepositSurety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, verbose_name='상품명')),
                ('amount', models.BigIntegerField(default=0, verbose_name='가입금액')),
                ('status', models.CharField(blank=True, default='', max_length=50, verbose_name='상태')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='보험가입일')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='보험종료일')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposit_sureties', to=settings.AUTH_USER_MODEL, verbose_name='사번')),
            ],
            options={
                'verbose_name': '보증보험',
                'verbose_name_plural': '보증보험',
                'db_table': 'deposit_surety',
            },
        ),
        migrations.CreateModel(
            name='DepositUploadLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part', models.CharField(db_index=True, max_length=50, verbose_name='부서')),
                ('upload_type', models.CharField(db_index=True, max_length=50, verbose_name='업로드 구분')),
                ('uploaded_at', models.DateTimeField(auto_now=True, verbose_name='마지막 업로드 일시')),
                ('row_count', models.IntegerField(default=0, verbose_name='반영 건수')),
                ('file_name', models.CharField(blank=True, default='', max_length=255, verbose_name='파일명')),
            ],
            options={
                'verbose_name': '채권 업로드 로그',
                'verbose_name_plural': '채권 업로드 로그',
                'db_table': 'deposit_upload_log',
                'unique_together': {('part', 'upload_type')},
            },
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
