# Generated by Django 5.2.7 on 2025-12-30 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commission', '0002_depositother_depositsummary_depositsurety_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='depositsummary',
            name='ls_25_total',
        ),
        migrations.RemoveField(
            model_name='depositsummary',
            name='ns_25_total',
        ),
        migrations.AddField(
            model_name='depositsummary',
            name='div_1m',
            field=models.BigIntegerField(default=0, verbose_name='1개월전분급'),
        ),
        migrations.AddField(
            model_name='depositsummary',
            name='div_2m',
            field=models.BigIntegerField(default=0, verbose_name='2개월전분급'),
        ),
        migrations.AddField(
            model_name='depositsummary',
            name='div_3m',
            field=models.BigIntegerField(default=0, verbose_name='3개월전분급'),
        ),
        migrations.AddField(
            model_name='depositsummary',
            name='inst_current',
            field=models.BigIntegerField(default=0, verbose_name='당월인정계속분'),
        ),
        migrations.AddField(
            model_name='depositsummary',
            name='int_prev',
            field=models.BigIntegerField(default=0, verbose_name='전월인정계속분'),
        ),
        migrations.AddField(
            model_name='depositsummary',
            name='maint_total',
            field=models.BigIntegerField(default=0, verbose_name='손생합산통산'),
        ),
        migrations.AddField(
            model_name='depositsummary',
            name='sales_total',
            field=models.BigIntegerField(default=0, verbose_name='장기총실적'),
        ),
    ]
