# Generated by Django 5.2.7 on 2025-12-31 01:27

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commission', '0003_remove_depositsummary_ls_25_total_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='depositsummary',
            name='ls_25_total_2',
        ),
        migrations.RemoveField(
            model_name='depositsummary',
            name='ns_18_total_2',
        ),
        migrations.RemoveField(
            model_name='depositsummary',
            name='ns_25_total_2',
        ),
        migrations.AddField(
            model_name='depositsummary',
            name='ls_18_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, verbose_name='18회생보통산'),
        ),
        migrations.AddField(
            model_name='depositsummary',
            name='ls_25_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, verbose_name='25회생보통산'),
        ),
        migrations.AddField(
            model_name='depositsummary',
            name='ns_25_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, verbose_name='25회손보통산'),
        ),
        migrations.AlterField(
            model_name='depositsummary',
            name='div_1m',
            field=models.CharField(blank=True, choices=[('정상', '정상'), ('분급', '분급')], default='', max_length=10, verbose_name='1개월전분급'),
        ),
        migrations.AlterField(
            model_name='depositsummary',
            name='div_2m',
            field=models.CharField(blank=True, choices=[('정상', '정상'), ('분급', '분급')], default='', max_length=10, verbose_name='2개월전분급'),
        ),
        migrations.AlterField(
            model_name='depositsummary',
            name='div_3m',
            field=models.CharField(blank=True, choices=[('정상', '정상'), ('분급', '분급')], default='', max_length=10, verbose_name='3개월전분급'),
        ),
        migrations.AlterField(
            model_name='depositsummary',
            name='ls_2_13_due',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, verbose_name='2-13회생보응당'),
        ),
        migrations.AlterField(
            model_name='depositsummary',
            name='ls_2_6_due',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, verbose_name='2-6회생보응당'),
        ),
        migrations.AlterField(
            model_name='depositsummary',
            name='maint_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, verbose_name='손생합산통산'),
        ),
        migrations.AlterField(
            model_name='depositsummary',
            name='ns_18_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, verbose_name='18회손보통산'),
        ),
        migrations.AlterField(
            model_name='depositsummary',
            name='ns_2_13_due',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, verbose_name='2-13회손보응당'),
        ),
        migrations.AlterField(
            model_name='depositsummary',
            name='ns_2_6_due',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, verbose_name='2-6회손보응당'),
        ),
    ]
