# Generated by Django 5.2.7 on 2026-01-01 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commission', '0004_remove_depositsummary_ls_25_total_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='depositother',
            name='product_type',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='보증내용'),
        ),
        migrations.AddField(
            model_name='depositother',
            name='status',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='상태'),
        ),
    ]
