# Generated by Django 5.2.7 on 2026-01-02 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commission', '0005_depositother_product_type_depositother_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='depositsummary',
            old_name='int_prev',
            new_name='inst_prev',
        ),
    ]
