# Generated by Django 5.2.7 on 2026-01-02 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commission', '0006_rename_int_prev_depositsummary_inst_prev'),
    ]

    operations = [
        migrations.AddField(
            model_name='depositsurety',
            name='policy_no',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='증권번호'),
        ),
    ]
