# Generated by Django 5.2.7 on 2026-01-02 06:45

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commission', '0007_depositsurety_policy_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='depositsummary',
            name='ls_13_round',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, verbose_name='13회생보회차'),
        ),
        migrations.AddField(
            model_name='depositsummary',
            name='ls_18_round',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, verbose_name='18회생보회차'),
        ),
        migrations.AddField(
            model_name='depositsummary',
            name='ns_13_round',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, verbose_name='13회손보회차'),
        ),
        migrations.AddField(
            model_name='depositsummary',
            name='ns_18_round',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, verbose_name='18회손보회차'),
        ),
    ]
