# Generated by Django 5.2.7 on 2026-01-02 06:50

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commission', '0008_depositsummary_ls_13_round_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depositsummary',
            name='ls_13_round',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='13회생보회차'),
        ),
        migrations.AlterField(
            model_name='depositsummary',
            name='ls_18_round',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='18회생보회차'),
        ),
        migrations.AlterField(
            model_name='depositsummary',
            name='ls_18_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='18회생보통산'),
        ),
        migrations.AlterField(
            model_name='depositsummary',
            name='ls_25_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='25회생보통산'),
        ),
        migrations.AlterField(
            model_name='depositsummary',
            name='ls_2_13_due',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='2-13회생보응당'),
        ),
        migrations.AlterField(
            model_name='depositsummary',
            name='ls_2_6_due',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='2-6회생보응당'),
        ),
        migrations.AlterField(
            model_name='depositsummary',
            name='ns_13_round',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='13회손보회차'),
        ),
        migrations.AlterField(
            model_name='depositsummary',
            name='ns_18_round',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='18회손보회차'),
        ),
        migrations.AlterField(
            model_name='depositsummary',
            name='ns_18_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='18회손보통산'),
        ),
        migrations.AlterField(
            model_name='depositsummary',
            name='ns_25_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='25회손보통산'),
        ),
        migrations.AlterField(
            model_name='depositsummary',
            name='ns_2_13_due',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='2-13회손보응당'),
        ),
        migrations.AlterField(
            model_name='depositsummary',
            name='ns_2_6_due',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='2-6회손보응당'),
        ),
    ]
