# Generated by Django 5.2.7 on 2026-01-08 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commission', '0009_alter_depositsummary_ls_13_round_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='depositsummary',
            name='surety_o_pay_ls',
            field=models.BigIntegerField(default=0, verbose_name='보증(O) 지급생보'),
        ),
        migrations.AddField(
            model_name='depositsummary',
            name='surety_o_pay_ns',
            field=models.BigIntegerField(default=0, verbose_name='보증(O) 지급손보'),
        ),
        migrations.AddField(
            model_name='depositsummary',
            name='surety_o_pay_total',
            field=models.BigIntegerField(default=0, verbose_name='보증(O) 지급합계'),
        ),
        migrations.AddField(
            model_name='depositsummary',
            name='surety_o_refund_ls',
            field=models.BigIntegerField(default=0, verbose_name='보증(O) 환수생보'),
        ),
        migrations.AddField(
            model_name='depositsummary',
            name='surety_o_refund_ns',
            field=models.BigIntegerField(default=0, verbose_name='보증(O) 환수손보'),
        ),
        migrations.AddField(
            model_name='depositsummary',
            name='surety_o_refund_total',
            field=models.BigIntegerField(default=0, verbose_name='보증(O) 환수합계'),
        ),
        migrations.AddField(
            model_name='depositsummary',
            name='surety_x_pay_ls',
            field=models.BigIntegerField(default=0, verbose_name='보증(X) 지급생보'),
        ),
        migrations.AddField(
            model_name='depositsummary',
            name='surety_x_pay_ns',
            field=models.BigIntegerField(default=0, verbose_name='보증(X) 지급손보'),
        ),
        migrations.AddField(
            model_name='depositsummary',
            name='surety_x_pay_total',
            field=models.BigIntegerField(default=0, verbose_name='보증(X) 지급합계'),
        ),
        migrations.AddField(
            model_name='depositsummary',
            name='surety_x_refund_ls',
            field=models.BigIntegerField(default=0, verbose_name='보증(X) 환수생보'),
        ),
        migrations.AddField(
            model_name='depositsummary',
            name='surety_x_refund_ns',
            field=models.BigIntegerField(default=0, verbose_name='보증(X) 환수손보'),
        ),
        migrations.AddField(
            model_name='depositsummary',
            name='surety_x_refund_total',
            field=models.BigIntegerField(default=0, verbose_name='보증(X) 환수합계'),
        ),
    ]
