# Generated by Django 5.2.7 on 2026-01-12 06:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commission', '0010_depositsummary_surety_o_pay_ls_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalExcelUploadLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ym', models.CharField(db_index=True, max_length=7, verbose_name='월도(YYYY-MM)')),
                ('kind', models.CharField(choices=[('efficiency', '지점효율'), ('approval', '수수료결재')], db_index=True, max_length=20, verbose_name='구분')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='업로드 일시')),
                ('row_count', models.IntegerField(default=0, verbose_name='행 수(추정)')),
                ('file_name', models.CharField(blank=True, default='', max_length=255, verbose_name='파일명')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_excel_upload_logs', to=settings.AUTH_USER_MODEL, verbose_name='업로드 사용자')),
            ],
            options={
                'verbose_name': '결재/효율 엑셀 업로드 로그',
                'verbose_name_plural': '결재/효율 엑셀 업로드 로그',
                'db_table': 'approval_excel_upload_log',
                'ordering': ['-uploaded_at'],
                'unique_together': {('ym', 'kind')},
            },
        ),
    ]
