# Generated by Django 5.2.7 on 2026-01-12 08:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commission', '0011_approvalexceluploadlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionApprovalPending',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ym', models.CharField(db_index=True, max_length=7, verbose_name='월도(YYYY-MM)')),
                ('emp_name', models.CharField(blank=True, default='', max_length=200, verbose_name='사원명(엑셀)')),
                ('actual_paid', models.BigIntegerField(default=0, verbose_name='실지급액')),
                ('approval', models.CharField(blank=True, default='', max_length=50, verbose_name='결재')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commission_approval_pendings', to=settings.AUTH_USER_MODEL, verbose_name='사번')),
            ],
            options={
                'verbose_name': '수수료 미결현황',
                'verbose_name_plural': '수수료 미결현황',
                'db_table': 'commission_approval_pending',
                'ordering': ['-ym', 'user_id'],
                'unique_together': {('ym', 'user')},
            },
        ),
    ]
