# Generated by Django 5.2.7 on 2026-01-13 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commission', '0013_approvalpending'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='approvalexceluploadlog',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='approvalexceluploadlog',
            name='part',
            field=models.CharField(blank=True, db_index=True, default='', max_length=50, verbose_name='부서'),
        ),
        migrations.AlterUniqueTogether(
            name='approvalexceluploadlog',
            unique_together={('ym', 'part', 'kind')},
        ),
        migrations.DeleteModel(
            name='CommissionApprovalPending',
        ),
    ]
