# Generated by Django 5.2.7 on 2026-01-14 14:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commission', '0014_alter_approvalexceluploadlog_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EfficiencyPayExcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ym', models.CharField(db_index=True, max_length=7, verbose_name='월도(YYYY-MM)')),
                ('pay_amount_sum', models.BigIntegerField(default=0, verbose_name='지급금액합계')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='efficiency_pay_excesses', to=settings.AUTH_USER_MODEL, verbose_name='사번')),
            ],
            options={
                'verbose_name': '지점효율지급 초과현황',
                'verbose_name_plural': '지점효율지급 초과현황',
                'db_table': 'efficiency_pay_excess',
                'ordering': ['ym', 'user_id'],
                'unique_together': {('ym', 'user')},
            },
        ),
    ]
