# Generated by Django 5.2.7 on 2026-02-03 06:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commission', '0015_efficiencypayexcess'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deposituploadlog',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='approvalexceluploadlog',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='approvalpending',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='deposituploadlog',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='efficiencypayexcess',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='approvalexceluploadlog',
            name='uploaded_at',
            field=models.DateTimeField(auto_now=True, verbose_name='업로드 일시'),
        ),
        migrations.AlterField(
            model_name='depositsummary',
            name='div_1m',
            field=models.CharField(blank=True, choices=[('', '-'), ('정상', '정상'), ('분급', '분급')], default='', max_length=10, verbose_name='1개월전분급'),
        ),
        migrations.AlterField(
            model_name='depositsummary',
            name='div_2m',
            field=models.CharField(blank=True, choices=[('', '-'), ('정상', '정상'), ('분급', '분급')], default='', max_length=10, verbose_name='2개월전분급'),
        ),
        migrations.AlterField(
            model_name='depositsummary',
            name='div_3m',
            field=models.CharField(blank=True, choices=[('', '-'), ('정상', '정상'), ('분급', '분급')], default='', max_length=10, verbose_name='3개월전분급'),
        ),
        migrations.AlterField(
            model_name='deposituploadlog',
            name='file_name',
            field=models.CharField(blank=True, db_column='file_name', default='', max_length=255, verbose_name='파일명'),
        ),
        migrations.AlterField(
            model_name='deposituploadlog',
            name='row_count',
            field=models.IntegerField(db_column='row_count', default=0, verbose_name='행 수(추정)'),
        ),
        migrations.AddConstraint(
            model_name='approvalexceluploadlog',
            constraint=models.UniqueConstraint(fields=('ym', 'part', 'kind'), name='uq_approval_exceluploadlog_ym_part_kind'),
        ),
        migrations.AddConstraint(
            model_name='approvalpending',
            constraint=models.UniqueConstraint(fields=('ym', 'user'), name='uq_approval_pending_ym_user'),
        ),
        migrations.AddConstraint(
            model_name='deposituploadlog',
            constraint=models.UniqueConstraint(fields=('part', 'upload_type'), name='uq_deposit_uploadlog_part_type'),
        ),
        migrations.AddConstraint(
            model_name='efficiencypayexcess',
            constraint=models.UniqueConstraint(fields=('ym', 'user'), name='uq_efficiency_payexcess_ym_user'),
        ),
    ]
