# Generated by Django 5.2.7 on 2026-02-03 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commission', '0016_alter_deposituploadlog_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deposituploadlog',
            options={'verbose_name': '채권 업로드 로그', 'verbose_name_plural': '채권 업로드 로그'},
        ),
        migrations.AlterField(
            model_name='deposituploadlog',
            name='file_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='파일명'),
        ),
        migrations.AlterField(
            model_name='deposituploadlog',
            name='row_count',
            field=models.IntegerField(default=0, verbose_name='행 수(추정)'),
        ),
    ]
