# Generated by Django 5.2.7 on 2026-02-03 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commission', '0017_alter_deposituploadlog_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deposituploadlog',
            options={},
        ),
    ]
