# Generated by Django 5.2.7 on 2025-10-13 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': '사용자', 'verbose_name_plural': '사용자'},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='branch',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='grade',
            field=models.CharField(choices=[('superuser', 'Superuser'), ('admin', 'Admin'), ('staff', 'Staff'), ('inactive', 'Inactive')], default='staff', max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='status',
            field=models.CharField(default='재직', max_length=20),
        ),
    ]
