# Generated by Django 5.2.7 on 2025-10-13 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_options_alter_customuser_branch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='grade',
            field=models.CharField(choices=[('superuser', 'Superuser'), ('staff', 'Staff'), ('fa', 'FA'), ('inactive', 'Inactive')], default='fa', max_length=20),
        ),
    ]
