# Generated by Django 5.2.7 on 2025-10-13 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_grade'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'users', 'verbose_name_plural': 'users'},
        ),
    ]
