# Generated by Django 5.2.7 on 2025-10-13 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customuser_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='grade',
            field=models.CharField(choices=[('superuser', 'Superuser'), ('admin', 'Admin'), ('basic', 'Basic'), ('inactive', 'Inactive')], default='basic', max_length=20),
        ),
    ]
