# Generated by Django 5.2.7 on 2025-10-18 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_customuser_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='birth',
            field=models.DateField(blank=True, null=True, verbose_name='생년월일'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='enter',
            field=models.DateField(blank=True, null=True, verbose_name='입사일자'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='quit',
            field=models.DateField(blank=True, null=True, verbose_name='퇴사일자'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='regist',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
