# Generated by Django 5.2.7 on 2025-10-18 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_customuser_birth_customuser_enter_customuser_quit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='regist',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
