# Generated by Django 5.2.7 on 2025-10-21 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_customuser_regist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='grade',
            field=models.CharField(choices=[('superuser', 'Superuser'), ('mainAdmin', 'Main_Admin'), ('subAdmin', 'Sub_Admin'), ('basic', 'Basic'), ('inactive', 'Inactive')], default='basic', max_length=20),
        ),
    ]
