# Generated by Django 5.2.7 on 2025-10-21 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_customuser_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='grade',
            field=models.CharField(choices=[('superuser', 'Superuser'), ('main_admin', 'Main Admin'), ('sub_admin', 'Sub Admin'), ('basic', 'Basic'), ('inactive', 'Inactive')], default='basic', max_length=20),
        ),
    ]
