# Generated by Django 5.2.7 on 2025-10-24 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_customuser_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='channel',
            field=models.CharField(blank=True, default='MA부문', max_length=10, verbose_name='부문'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='part',
            field=models.CharField(blank=True, default='MA사업4부', max_length=10, verbose_name='부서'),
        ),
    ]
