# Generated by Django 5.2.7 on 2026-01-23 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_customuser_channel_customuser_part'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='division',
            field=models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='총괄'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='channel',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='부문'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='part',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='부서'),
        ),
    ]
