# Generated by Django 5.2.7 on 2026-01-23 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_customuser_division_alter_customuser_channel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='grade',
            field=models.CharField(choices=[('superuser', 'Superuser'), ('main_admin', 'Main Admin'), ('sub_admin', 'Sub Admin'), ('basic', 'Basic'), ('resign', 'Resign'), ('inactive', 'Inactive')], default='basic', max_length=20),
        ),
    ]
