# Generated by Django 5.2.7 on 2026-01-23 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_customuser_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='branch',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='지점'),
        ),
    ]
