# Generated by Django 5.2.7 on 2026-01-24 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_customuser_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='grade',
            field=models.CharField(choices=[('superuser', 'Superuser'), ('main_admin', 'Main Admin'), ('head', 'Head'), ('sub_admin', 'Sub Admin'), ('leader', 'Leader'), ('basic', 'Basic'), ('resign', 'Resign'), ('inactive', 'Inactive')], default='basic', max_length=20),
        ),
    ]
