# Generated by Django 5.2.7 on 2026-02-07 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_customuser_grade'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='branch',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='지점'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='division',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='총괄'),
        ),
    ]
