# Generated by Django 5.2.7 on 2025-10-15 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='joininfo',
            name='user_branch',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='소속'),
        ),
        migrations.AddField(
            model_name='joininfo',
            name='user_id',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='사번'),
        ),
        migrations.AddField(
            model_name='joininfo',
            name='user_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='성명'),
        ),
    ]
