# Generated by Django 5.2.4 on 2025-09-30 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('join', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Visitor',
            new_name='JoinInfo',
        ),
    ]
