# Generated by Django 5.2.6 on 2025-10-10 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join', '0002_rename_visitor_joininfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='joininfo',
            name='address_detail',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='joininfo',
            name='postcode',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='joininfo',
            name='address',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='joininfo',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
