# Generated by Django 5.2.6 on 2025-10-10 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join', '0003_joininfo_address_detail_joininfo_postcode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joininfo',
            name='postcode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
