"""
Django settings for web_ma project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

# django_ma > web_ma > settings.py
import os
import logging
from pathlib import Path
import dj_database_url
from decouple import Config, RepositoryEnv

ENV = os.environ.get("ENV", "dev")

if ENV == "prod":
    config = Config(RepositoryEnv(".env.prod"))
else:
    config = Config(RepositoryEnv(".env.dev"))

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

SECRET_KEY = config("SECRET_KEY")
DEBUG = config("DEBUG", cast=bool, default=True)

ALLOWED_HOSTS = [
    "localhost",
    "127.0.0.1",
    "local.ma-support.kr",
    "ma-support.kr",
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'home',
    'join',
    'board',
    'accounts',
    'widget_tweaks',
    'commission',
    'dash',
    'partner.apps.PartnerConfig',
    'django_extensions',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
]

ROOT_URLCONF = 'web_ma.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'web_ma.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

if ENV == "prod":
    DATABASES = {
        "default": dj_database_url.config(
            default=config("DATABASE_URL"),
            conn_max_age=600,
            ssl_require=True,
        )
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": config("DB_NAME"),
            "USER": config("DB_USER"),
            "PASSWORD": config("DB_PASSWORD"),
            "HOST": config("DB_HOST"),
            "PORT": config("DB_PORT"),
            "OPTIONS": {"client_encoding": "UTF8"},
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTH_USER_MODEL = 'accounts.CustomUser'

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

# ====== 시간대 관련 설정 ======
LANGUAGE_CODE = 'ko-kr'
TIME_ZONE = 'Asia/Seoul'

USE_I18N = True
USE_L10N = True
USE_TZ = True  # ✅ True 유지! (시간대 인식형 datetime 사용)

# 선택: 표시 형식 조정
DATETIME_FORMAT = 'Y-m-d H:i'
DATE_FORMAT = 'Y-m-d'


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

# This setting informs Django of the URI path from which your static files will be served to users
# Here, they well be accessible at your-domain.onrender.com/static/... or yourcustomdomain.com/static/...
STATIC_URL = '/static/'

STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# This production code might break development mode, so we check whether we're in DEBUG mode
if not DEBUG:
    # Tell Django to copy static assets into a path called `staticfiles` (this is specific to Render)
    STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

    # Enable the WhiteNoise storage backend, which compresses static files to reduce disk use
    # and renames the files with unique names for each version to support long-term caching
    STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_URL = '/login/'  # 로그인하지 않은 사용자가 리디렉션될 URL
LOGIN_REDIRECT_URL = '/'  # 로그인 후 이동할 URL
LOGOUT_REDIRECT_URL = '/'  # 로그아웃 후 이동할 URL

# settings.py 또는 celery.py
REDIS_URL = os.environ.get("REDIS_URL", "redis://localhost:6379/0")

CELERY_BROKER_URL = 'redis://localhost:6379/0'
CELERY_RESULT_BACKEND = 'redis://localhost:6379/0'

# --- 세션 관리 설정 (Render 배포용 최종본) ---

# ✅ 1. 브라우저 닫으면 즉시 로그아웃
SESSION_EXPIRE_AT_BROWSER_CLOSE = True

# ✅ 2. 1시간(3600초) 동안 활동 없으면 자동 로그아웃
SESSION_COOKIE_AGE = 3600  # 초 단위
SESSION_SAVE_EVERY_REQUEST = True  # 요청 있을 때마다 만료 시간 갱신

# ✅ 3. 세션 저장소: DB
SESSION_ENGINE = 'django.contrib.sessions.backends.db'

# ✅ 4. 보안 강화를 위한 쿠키 설정
SESSION_COOKIE_HTTPONLY = True       # 자바스크립트에서 접근 불가
SESSION_COOKIE_SECURE = True         # HTTPS 전용 (Render는 자동 HTTPS)
CSRF_COOKIE_SECURE = True            # CSRF 쿠키도 HTTPS 전용
CSRF_COOKIE_HTTPONLY = True          # JS 접근 차단 (보안 강화)
CSRF_TRUSTED_ORIGINS = [
    "https://local.ma-support.kr",
    "https://ma-support.kr",
]



# ✅ 5. 추가 옵션 (권장)
# 세션 쿠키 이름 (기본값: 'sessionid', 필요 시 커스터마이징 가능)
# SESSION_COOKIE_NAME = 'ma_session'

# ✅ 6. 개발 중에는 아래처럼 조정 가능 (DEBUG=True일 경우)
# if DEBUG:
#     SESSION_COOKIE_SECURE = False
#     CSRF_COOKIE_SECURE = False

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'access.log',
        },
    },
    'loggers': {
        'django.security.*': {
            'handlers': ['file'],
            'level': 'INFO',
            'propagate': True,
        },
        'accounts.access': {  # 👈 custom logger 사용 시
            'handlers': ['file'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}

logging.getLogger("django.server").setLevel(logging.ERROR)

# 파일첨부 기능을 위한 media url 설정
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# 업로드 시 필드 수 제한 해제 또는 확장
DATA_UPLOAD_MAX_NUMBER_FIELDS = 10000

UPLOAD_RESULT_DIR = MEDIA_ROOT / "upload_results"
UPLOAD_TEMP_DIR = MEDIA_ROOT / "upload_temp"