# Generated by Django 5.2.7 on 2026-01-17 09:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesRecord',
            fields=[
                ('policy_no', models.CharField(max_length=60, primary_key=True, serialize=False, verbose_name='증권번호')),
                ('part_snapshot', models.CharField(blank=True, max_length=30, null=True, verbose_name='부서(스냅샷)')),
                ('branch_snapshot', models.CharField(blank=True, max_length=100, null=True, verbose_name='지점(스냅샷)')),
                ('name_snapshot', models.CharField(blank=True, max_length=100, null=True, verbose_name='성명(스냅샷)')),
                ('emp_id_snapshot', models.CharField(blank=True, max_length=30, null=True, verbose_name='사원번호(스냅샷)')),
                ('insurer', models.CharField(db_index=True, max_length=60, verbose_name='보험사')),
                ('contractor', models.CharField(blank=True, max_length=100, null=True, verbose_name='계약자')),
                ('main_premium', models.CharField(blank=True, max_length=50, null=True, verbose_name='주피')),
                ('ins_start', models.DateField(blank=True, null=True, verbose_name='보험시작')),
                ('ins_end', models.DateField(blank=True, null=True, verbose_name='보험종기')),
                ('pay_method', models.CharField(blank=True, max_length=30, null=True, verbose_name='납입방법')),
                ('receipt_date', models.DateField(blank=True, db_index=True, null=True, verbose_name='영수일자')),
                ('receipt_amount', models.BigIntegerField(blank=True, null=True, verbose_name='영수금')),
                ('product_code', models.CharField(blank=True, max_length=60, null=True, verbose_name='보험사 상품코드')),
                ('product_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='보험사 상품명')),
                ('life_nl', models.CharField(choices=[('손보', '손보'), ('생보', '생보'), ('기타', '기타')], db_index=True, default='기타', max_length=10, verbose_name='손생')),
                ('ym', models.CharField(db_index=True, max_length=7, verbose_name='월도(YYYY-MM)')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='업데이트')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_records', to=settings.AUTH_USER_MODEL, verbose_name='설계사')),
            ],
            options={
                'verbose_name': '매출레코드',
                'verbose_name_plural': '매출레코드',
                'db_table': 'dash_sales_record',
                'indexes': [models.Index(fields=['ym', 'insurer'], name='dash_sales__ym_593fbc_idx'), models.Index(fields=['ym', 'life_nl'], name='dash_sales__ym_a37621_idx'), models.Index(fields=['ym', 'user'], name='dash_sales__ym_5145da_idx')],
            },
        ),
    ]
