# Generated by Django 5.2.7 on 2026-01-17 12:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='salesrecord',
            name='car_liability',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='책임'),
        ),
        migrations.AddField(
            model_name='salesrecord',
            name='car_optional',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='임의'),
        ),
        migrations.AddField(
            model_name='salesrecord',
            name='car_status',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='상태'),
        ),
        migrations.AddField(
            model_name='salesrecord',
            name='vehicle_no',
            field=models.CharField(blank=True, db_index=True, max_length=40, null=True, verbose_name='차량번호'),
        ),
        migrations.AlterField(
            model_name='salesrecord',
            name='life_nl',
            field=models.CharField(choices=[('손보', '손보'), ('생보', '생보'), ('자동차', '자동차')], db_index=True, default='손보', max_length=10, verbose_name='손생'),
        ),
        migrations.AddIndex(
            model_name='salesrecord',
            index=models.Index(fields=['ym', 'vehicle_no'], name='dash_sales__ym_00e08a_idx'),
        ),
    ]
