# Generated by Django 5.2.7 on 2026-01-23 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0003_rename_car_status_salesrecord_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesrecord',
            name='insured',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='피보험자'),
        ),
    ]
