# Generated by Django 5.2.7 on 2026-01-10 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manual', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manual',
            name='admin_only',
            field=models.BooleanField(default=False),
        ),
    ]
