# Generated by Django 5.2.7 on 2026-01-11 01:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manual', '0003_alter_manual_options_manual_sort_order_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='manual.manual')),
            ],
            options={
                'ordering': ['sort_order', 'created_at'],
            },
        ),
    ]
