# Generated by Django 5.2.7 on 2026-01-11 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manual', '0004_manualblock'),
    ]

    operations = [
        migrations.AddField(
            model_name='manualblock',
            name='title',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
