# Generated by Django 5.2.7 on 2026-01-11 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manual', '0006_manualsection_manualblock_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='manualblock',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='manual/blocks/'),
        ),
    ]
