# Generated by Django 5.2.7 on 2026-01-12 00:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manual', '0007_manualblock_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualBlockAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='manual/attachments/')),
                ('original_name', models.CharField(blank=True, default='', max_length=255)),
                ('size', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='manual.manualblock')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
    ]
