# Generated by Django 5.2.7 on 2026-02-07 02:45

import django.db.models.deletion
import manual.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manual', '0008_manualblockattachment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='manual',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manuals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='manualblockattachment',
            name='file',
            field=models.FileField(upload_to='manual/attachments/', validators=[manual.models.validate_attachment_size]),
        ),
        migrations.AddIndex(
            model_name='manual',
            index=models.Index(fields=['sort_order'], name='manual_manu_sort_or_a057ef_idx'),
        ),
        migrations.AddIndex(
            model_name='manual',
            index=models.Index(fields=['-updated_at'], name='manual_manu_updated_ab0b54_idx'),
        ),
        migrations.AddIndex(
            model_name='manualblock',
            index=models.Index(fields=['manual', 'sort_order'], name='manual_manu_manual__564c1e_idx'),
        ),
        migrations.AddIndex(
            model_name='manualblock',
            index=models.Index(fields=['section', 'sort_order'], name='manual_manu_section_c2fbe5_idx'),
        ),
        migrations.AddIndex(
            model_name='manualblockattachment',
            index=models.Index(fields=['block', 'created_at'], name='manual_manu_block_i_a19d05_idx'),
        ),
        migrations.AddIndex(
            model_name='manualsection',
            index=models.Index(fields=['manual', 'sort_order'], name='manual_manu_manual__350252_idx'),
        ),
    ]
