# Generated by Django 5.2.7 on 2025-10-15 00:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_post_category_post_code_post_fa_post_insu_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(blank=True, default='', max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='code',
            field=models.IntegerField(blank=True, default=1600000, null=True, validators=[django.core.validators.MinValueValidator(1600000), django.core.validators.MaxValueValidator(3000000)]),
        ),
        migrations.AlterField(
            model_name='post',
            name='fa',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='insu',
            field=models.CharField(blank=True, default='', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='serial',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
    ]
