# Generated by Django 5.2.7 on 2025-10-15 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_alter_post_category_alter_post_code_alter_post_fa_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='insu',
        ),
        migrations.RemoveField(
            model_name='post',
            name='serial',
        ),
    ]
