# Generated by Django 5.2.7 on 2025-10-15 05:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_remove_post_insu_remove_post_serial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='code',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1600000), django.core.validators.MaxValueValidator(3000000)]),
        ),
    ]
