# Generated by Django 5.2.7 on 2025-10-15 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_alter_post_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='user_branch',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='user_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='user_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
