# Generated by Django 5.2.7 on 2025-10-15 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0007_alter_post_options_post_receipt_number_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at'], 'verbose_name': '업무요청 게시글', 'verbose_name_plural': '업무요청 게시글'},
        ),
        migrations.AddField(
            model_name='post',
            name='handler',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('확인중', '확인중'), ('진행중', '진행중'), ('보완요청', '보완요청'), ('완료', '완료'), ('반려', '반려')], default='확인중', max_length=20),
        ),
        migrations.AddField(
            model_name='post',
            name='status_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
