# Generated by Django 5.2.7 on 2025-10-15 14:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0008_alter_post_options_post_handler_post_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at'], 'verbose_name': 'Posts', 'verbose_name_plural': 'Posts'},
        ),
        migrations.AddField(
            model_name='post',
            name='attachment',
            field=models.FileField(blank=True, help_text='첨부파일이 있는 경우 업로드하세요.', null=True, upload_to='uploads/%Y/%m/%d/', verbose_name='첨부파일'),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(blank=True, default='', max_length=7, verbose_name='구분'),
        ),
        migrations.AlterField(
            model_name='post',
            name='code',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1600000), django.core.validators.MaxValueValidator(3000000)], verbose_name='사번(대상자)'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(verbose_name='요청 내용'),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='최초등록일'),
        ),
        migrations.AlterField(
            model_name='post',
            name='fa',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='성명(대상자)'),
        ),
        migrations.AlterField(
            model_name='post',
            name='handler',
            field=models.CharField(blank=True, default='', help_text='담당자(슈퍼유저 이름)', max_length=100, verbose_name='담당자'),
        ),
        migrations.AlterField(
            model_name='post',
            name='receipt_number',
            field=models.CharField(blank=True, help_text='자동 생성 (예: 20251015001)', max_length=20, unique=True, verbose_name='접수번호'),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('확인중', '확인중'), ('진행중', '진행중'), ('보완요청', '보완요청'), ('완료', '완료'), ('반려', '반려')], default='확인중', max_length=20, verbose_name='상태'),
        ),
        migrations.AlterField(
            model_name='post',
            name='status_updated_at',
            field=models.DateTimeField(blank=True, help_text='상태나 담당자가 변경된 시점', null=True, verbose_name='상태변경일'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=200, verbose_name='제목'),
        ),
        migrations.AlterField(
            model_name='post',
            name='user_branch',
            field=models.CharField(blank=True, max_length=100, verbose_name='소속(요청자)'),
        ),
        migrations.AlterField(
            model_name='post',
            name='user_id',
            field=models.CharField(blank=True, max_length=30, verbose_name='사번(요청자)'),
        ),
        migrations.AlterField(
            model_name='post',
            name='user_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='성명(요청자)'),
        ),
    ]
