# Generated by Django 5.2.7 on 2025-10-17 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0009_alter_post_options_post_attachment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='attachment',
        ),
    ]
