# Generated by Django 5.2.7 on 2025-11-02 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0012_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attachment',
            options={'verbose_name': '첨부파일', 'verbose_name_plural': '첨부파일 목록'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at'], 'verbose_name': '댓글', 'verbose_name_plural': '댓글 목록'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at'], 'verbose_name': '업무요청 게시글', 'verbose_name_plural': '업무요청 게시글 목록'},
        ),
        migrations.AlterField(
            model_name='attachment',
            name='content_type',
            field=models.CharField(blank=True, max_length=120, verbose_name='MIME 타입'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='original_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='원본 파일명'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='size',
            field=models.PositiveBigIntegerField(default=0, verbose_name='파일 크기'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='업로드일'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(max_length=500, verbose_name='댓글 내용'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='작성일시'),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='구분'),
        ),
        migrations.AlterField(
            model_name='post',
            name='status_updated_at',
            field=models.DateTimeField(blank=True, help_text='상태나 담당자가 변경된 시점 자동기록', null=True, verbose_name='상태변경일'),
        ),
    ]
