# Generated by Django 5.2.7 on 2025-12-29 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0013_alter_attachment_options_alter_comment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='handler',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='담당자'),
        ),
        migrations.AlterField(
            model_name='post',
            name='receipt_number',
            field=models.CharField(blank=True, max_length=20, unique=True, verbose_name='접수번호'),
        ),
        migrations.AlterField(
            model_name='post',
            name='status_updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='상태변경일'),
        ),
    ]
