# Generated by Django 5.2.7 on 2026-01-04 09:57

import board.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0014_alter_post_handler_alter_post_receipt_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(blank=True, max_length=20, unique=True, verbose_name='접수번호')),
                ('category', models.CharField(blank=True, default='', max_length=10, verbose_name='구분')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('content', models.TextField(verbose_name='요청 내용')),
                ('user_id', models.CharField(blank=True, default='', max_length=30, verbose_name='사번(요청자)')),
                ('user_name', models.CharField(blank=True, default='', max_length=100, verbose_name='성명(요청자)')),
                ('user_branch', models.CharField(blank=True, default='', max_length=100, verbose_name='소속(요청자)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='최초등록일')),
                ('handler', models.CharField(blank=True, default='', max_length=100, verbose_name='담당자')),
                ('status', models.CharField(choices=[('확인중', '확인중'), ('진행중', '진행중'), ('보완요청', '보완요청'), ('완료', '완료'), ('반려', '반려')], default='확인중', max_length=20, verbose_name='상태')),
                ('status_updated_at', models.DateTimeField(blank=True, null=True, verbose_name='상태변경일')),
            ],
            options={
                'verbose_name': '직원업무 게시글',
                'verbose_name_plural': '직원업무 게시글 목록',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=board.models.task_attachment_upload_to)),
                ('original_name', models.CharField(blank=True, max_length=255, verbose_name='원본 파일명')),
                ('size', models.PositiveBigIntegerField(default=0, verbose_name='파일 크기')),
                ('content_type', models.CharField(blank=True, max_length=120, verbose_name='MIME 타입')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='업로드일')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='board.task')),
            ],
            options={
                'verbose_name': '직원업무 첨부파일',
                'verbose_name_plural': '직원업무 첨부파일 목록',
            },
        ),
        migrations.CreateModel(
            name='TaskComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=500, verbose_name='댓글 내용')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일시')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='board.task')),
            ],
            options={
                'verbose_name': '직원업무 댓글',
                'verbose_name_plural': '직원업무 댓글 목록',
                'ordering': ['-created_at'],
            },
        ),
    ]
