# Generated by Django 5.2.7 on 2026-01-09 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0015_task_taskattachment_taskcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('시작전', '시작전'), ('진행중', '진행중'), ('보완필요', '보완필요'), ('완료', '완료')], default='시작전', max_length=20, verbose_name='상태'),
        ),
    ]
