# Generated by Django 5.2.7 on 2025-10-24 12:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('detail', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StructureChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(blank=True, max_length=50, null=True)),
                ('target_branch', models.CharField(blank=True, max_length=50, null=True)),
                ('chg_branch', models.CharField(blank=True, max_length=50, null=True)),
                ('or_flag', models.BooleanField(default=False)),
                ('rank', models.CharField(blank=True, max_length=20, null=True)),
                ('chg_rank', models.CharField(blank=True, max_length=20, null=True)),
                ('table_name', models.CharField(blank=True, max_length=20, null=True)),
                ('chg_table', models.CharField(blank=True, max_length=20, null=True)),
                ('rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('chg_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('memo', models.CharField(blank=True, max_length=100, null=True)),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('process_date', models.DateTimeField(blank=True, null=True)),
                ('month', models.CharField(help_text='YYYY-MM', max_length=7)),
                ('requester', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='structure_requests', to=settings.AUTH_USER_MODEL)),
                ('target', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='structure_targets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
