# Generated by Django 5.2.7 on 2025-10-24 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StructureDeadline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(max_length=50)),
                ('month', models.CharField(max_length=7)),
                ('deadline_day', models.PositiveSmallIntegerField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('branch', 'month')},
            },
        ),
    ]
