# Generated by Django 5.2.7 on 2025-10-25 07:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0002_structuredeadline'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partnerchangelog',
            options={'ordering': ['-timestamp'], 'verbose_name': '편제변경 로그', 'verbose_name_plural': '편제변경 로그'},
        ),
        migrations.AlterModelOptions(
            name='structurechange',
            options={'ordering': ['-month', '-request_date'], 'verbose_name': '편제변경 데이터', 'verbose_name_plural': '편제변경 데이터'},
        ),
        migrations.AlterModelOptions(
            name='structuredeadline',
            options={'ordering': ['-month', 'branch'], 'verbose_name': '편제변경 마감일', 'verbose_name_plural': '편제변경 마감일'},
        ),
        migrations.AlterField(
            model_name='partnerchangelog',
            name='action',
            field=models.CharField(help_text='수행된 작업 유형 (save/delete/set_deadline 등)', max_length=50),
        ),
        migrations.AlterField(
            model_name='partnerchangelog',
            name='detail',
            field=models.TextField(blank=True, help_text='추가 상세 내역', null=True),
        ),
        migrations.AlterField(
            model_name='partnerchangelog',
            name='user',
            field=models.ForeignKey(help_text='작업자', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='structurechange',
            name='branch',
            field=models.CharField(blank=True, help_text='요청자 소속', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='structurechange',
            name='chg_branch',
            field=models.CharField(blank=True, help_text='변경 후 소속', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='structurechange',
            name='or_flag',
            field=models.BooleanField(default=False, help_text='OR 여부 플래그'),
        ),
        migrations.AlterField(
            model_name='structurechange',
            name='requester',
            field=models.ForeignKey(help_text='변경 요청자', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='structure_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='structurechange',
            name='target',
            field=models.ForeignKey(help_text='변경 대상자', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='structure_targets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='structurechange',
            name='target_branch',
            field=models.CharField(blank=True, help_text='대상자 기존 소속', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='structuredeadline',
            name='deadline_day',
            field=models.PositiveSmallIntegerField(help_text='마감 일자 (1~31)'),
        ),
        migrations.AlterField(
            model_name='structuredeadline',
            name='month',
            field=models.CharField(help_text='YYYY-MM', max_length=7),
        ),
        migrations.CreateModel(
            name='SubAdminTemp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('part', models.CharField(blank=True, max_length=50, null=True)),
                ('branch', models.CharField(blank=True, max_length=50, null=True)),
                ('grade', models.CharField(blank=True, max_length=20, null=True)),
                ('team_a', models.CharField(blank=True, max_length=50, null=True)),
                ('team_b', models.CharField(blank=True, max_length=50, null=True)),
                ('team_c', models.CharField(blank=True, max_length=50, null=True)),
                ('position', models.CharField(blank=True, max_length=30, null=True)),
                ('level', models.CharField(blank=True, max_length=30, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subadmin_detail', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '권한관리 확장정보',
                'verbose_name_plural': '권한관리 확장정보',
                'db_table': 'partner_subadmin_temp',
            },
        ),
    ]
