# Generated by Django 5.2.7 on 2025-10-26 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0003_alter_partnerchangelog_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subadmintemp',
            name='level',
            field=models.CharField(choices=[('-', '-'), ('A레벨', 'A레벨'), ('B레벨', 'B레벨'), ('C레벨', 'C레벨')], default='-', max_length=10, verbose_name='레벨'),
        ),
    ]
