# Generated by Django 5.2.7 on 2025-10-28 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0004_alter_subadmintemp_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='structurechange',
            name='part',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='부서'),
        ),
    ]
