# Generated by Django 5.2.7 on 2025-11-02 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0005_structurechange_part'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(max_length=100)),
                ('table_name', models.CharField(max_length=100)),
                ('rate', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['branch', 'table_name'],
                'unique_together': {('branch', 'table_name')},
            },
        ),
    ]
