# Generated by Django 5.2.7 on 2025-11-02 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0006_tablesetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablesetting',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='표시 순서'),
        ),
    ]
