# Generated by Django 5.2.7 on 2025-11-02 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0007_tablesetting_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablesetting',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
