# Generated by Django 5.2.7 on 2025-11-02 10:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0008_tablesetting_updated_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RateTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(blank=True, max_length=50, null=True, verbose_name='지점')),
                ('team_a', models.CharField(blank=True, max_length=50, null=True, verbose_name='팀A')),
                ('team_b', models.CharField(blank=True, max_length=50, null=True, verbose_name='팀B')),
                ('team_c', models.CharField(blank=True, max_length=50, null=True, verbose_name='팀C')),
                ('non_life_table', models.CharField(blank=True, max_length=100, null=True, verbose_name='손보 테이블명')),
                ('life_table', models.CharField(blank=True, max_length=100, null=True, verbose_name='생보 테이블명')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rate_table', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '요율관리 테이블',
                'verbose_name_plural': '요율관리 테이블',
                'ordering': ['branch', 'user__name'],
            },
        ),
    ]
