# Generated by Django 5.2.7 on 2025-12-23 03:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0009_ratetable'),
    ]

    operations = [
        migrations.AddField(
            model_name='structurechange',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
