# Generated by Django 5.2.7 on 2025-12-23 05:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0010_structurechange_created_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RateChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part', models.CharField(default='-', max_length=50)),
                ('branch', models.CharField(default='-', max_length=50)),
                ('month', models.CharField(db_index=True, max_length=7)),
                ('before_ftable', models.CharField(blank=True, default='', max_length=100)),
                ('before_frate', models.CharField(blank=True, default='', max_length=20)),
                ('before_ltable', models.CharField(blank=True, default='', max_length=100)),
                ('before_lrate', models.CharField(blank=True, default='', max_length=20)),
                ('after_ftable', models.CharField(blank=True, default='', max_length=100)),
                ('after_frate', models.CharField(blank=True, default='', max_length=20)),
                ('after_ltable', models.CharField(blank=True, default='', max_length=100)),
                ('after_lrate', models.CharField(blank=True, default='', max_length=20)),
                ('memo', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('process_date', models.DateField(blank=True, null=True)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratechange_requests', to=settings.AUTH_USER_MODEL)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratechange_targets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
                'indexes': [models.Index(fields=['month', 'branch'], name='partner_rat_month_7b28aa_idx')],
            },
        ),
    ]
