# Generated by Django 5.2.7 on 2025-12-28 13:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0011_ratechange'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EfficiencyChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part', models.CharField(default='-', max_length=50)),
                ('branch', models.CharField(default='-', max_length=50)),
                ('month', models.CharField(db_index=True, max_length=7)),
                ('target_branch', models.CharField(blank=True, default='', max_length=50)),
                ('chg_branch', models.CharField(blank=True, default='', max_length=50)),
                ('rank', models.CharField(blank=True, default='', max_length=20)),
                ('chg_rank', models.CharField(blank=True, default='', max_length=20)),
                ('or_flag', models.BooleanField(default=False)),
                ('memo', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('process_date', models.DateField(blank=True, null=True)),
                ('requester', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='efficiency_requests', to=settings.AUTH_USER_MODEL)),
                ('target', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='efficiency_targets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
                'indexes': [models.Index(fields=['month', 'branch'], name='partner_eff_month_b8d8a0_idx')],
            },
        ),
    ]
