# Generated by Django 5.2.7 on 2026-01-02 09:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0013_efficiencychange_amount_efficiencychange_category_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EfficiencyConfirmAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part', models.CharField(default='-', max_length=50, verbose_name='부서')),
                ('branch', models.CharField(default='-', max_length=50, verbose_name='지점')),
                ('month', models.CharField(db_index=True, max_length=7, verbose_name='월(YYYY-MM)')),
                ('file', models.FileField(upload_to='partner/efficiency_confirm/%Y/%m/', verbose_name='확인서 파일')),
                ('original_name', models.CharField(blank=True, default='', max_length=255, verbose_name='원본파일명')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='efficiency_confirm_uploads', to=settings.AUTH_USER_MODEL, verbose_name='업로더')),
            ],
            options={
                'verbose_name': '지점효율 확인서',
                'verbose_name_plural': '지점효율 확인서',
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='efficiencychange',
            name='confirm_attachment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='efficiency_rows', to='partner.efficiencyconfirmattachment', verbose_name='확인서'),
        ),
        migrations.AddIndex(
            model_name='efficiencyconfirmattachment',
            index=models.Index(fields=['month', 'branch'], name='partner_eff_month_75e5f8_idx'),
        ),
    ]
