# Generated by Django 5.2.7 on 2026-01-03 10:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0014_efficiencyconfirmattachment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EfficiencyConfirmGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirm_group_id', models.CharField(db_index=True, max_length=40, unique=True, verbose_name='확인서 그룹ID')),
                ('part', models.CharField(default='-', max_length=50, verbose_name='부서')),
                ('branch', models.CharField(default='-', max_length=50, verbose_name='지점')),
                ('month', models.CharField(db_index=True, max_length=7, verbose_name='월(YYYY-MM)')),
                ('title', models.CharField(blank=True, default='', max_length=120, verbose_name='제목')),
                ('note', models.CharField(blank=True, default='', max_length=200, verbose_name='비고')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='efficiency_confirm_groups', to=settings.AUTH_USER_MODEL, verbose_name='업로더')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='efficiencychange',
            name='confirm_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='efficiency_rows', to='partner.efficiencyconfirmgroup', verbose_name='확인서 그룹'),
        ),
        migrations.AddField(
            model_name='efficiencyconfirmattachment',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='partner.efficiencyconfirmgroup', verbose_name='확인서 그룹'),
        ),
        migrations.AddIndex(
            model_name='efficiencychange',
            index=models.Index(fields=['confirm_group'], name='partner_eff_confirm_fb74e3_idx'),
        ),
        migrations.AddIndex(
            model_name='efficiencychange',
            index=models.Index(fields=['confirm_attachment'], name='partner_eff_confirm_32bf30_idx'),
        ),
        migrations.AddIndex(
            model_name='efficiencyconfirmattachment',
            index=models.Index(fields=['group'], name='partner_eff_group_i_22657b_idx'),
        ),
        migrations.AddIndex(
            model_name='efficiencyconfirmgroup',
            index=models.Index(fields=['month', 'branch'], name='partner_eff_month_362e2f_idx'),
        ),
    ]
