# Generated by Django 5.2.7 on 2026-01-03 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0015_efficiencyconfirmgroup_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='efficiencyconfirmattachment',
            options={'ordering': ['-id'], 'verbose_name': '지점효율 확인서(파일)', 'verbose_name_plural': '지점효율 확인서(파일)'},
        ),
        migrations.AlterModelOptions(
            name='efficiencyconfirmgroup',
            options={'ordering': ['-id'], 'verbose_name': '지점효율 확인서(그룹)', 'verbose_name_plural': '지점효율 확인서(그룹)'},
        ),
        migrations.RemoveIndex(
            model_name='efficiencychange',
            name='partner_eff_confirm_fb74e3_idx',
        ),
        migrations.RemoveIndex(
            model_name='efficiencychange',
            name='partner_eff_confirm_32bf30_idx',
        ),
        migrations.RemoveIndex(
            model_name='efficiencyconfirmattachment',
            name='partner_eff_group_i_22657b_idx',
        ),
        migrations.RemoveField(
            model_name='efficiencyconfirmattachment',
            name='group',
        ),
        migrations.RemoveField(
            model_name='efficiencyconfirmgroup',
            name='note',
        ),
        migrations.RemoveField(
            model_name='efficiencyconfirmgroup',
            name='title',
        ),
        migrations.AddField(
            model_name='efficiencyconfirmgroup',
            name='attachment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='confirm_groups', to='partner.efficiencyconfirmattachment', verbose_name='첨부파일'),
        ),
        migrations.AlterField(
            model_name='efficiencychange',
            name='confirm_attachment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='efficiency_rows_legacy', to='partner.efficiencyconfirmattachment', verbose_name='확인서(레거시)'),
        ),
        migrations.AlterField(
            model_name='efficiencyconfirmgroup',
            name='confirm_group_id',
            field=models.CharField(db_index=True, max_length=64, unique=True, verbose_name='그룹ID'),
        ),
    ]
