# Generated by Django 5.2.7 on 2026-01-03 13:17

# django__ma/partner/migrations/0017_remove_efficiencychange_chg_branch_and_more.py

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0016_alter_efficiencyconfirmattachment_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='efficiencychange',
            name='chg_branch',
        ),
        migrations.RemoveField(
            model_name='efficiencychange',
            name='chg_rank',
        ),
        migrations.RemoveField(
            model_name='efficiencychange',
            name='or_flag',
        ),
        migrations.RemoveField(
            model_name='efficiencychange',
            name='rank',
        ),
        migrations.RemoveField(
            model_name='efficiencychange',
            name='target_branch',
        ),
        migrations.RemoveField(
            model_name='efficiencyconfirmgroup',
            name='attachment',
        ),
        migrations.AddField(
            model_name='efficiencyconfirmattachment',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='partner.efficiencyconfirmgroup', verbose_name='확인서 그룹'),
        ),
        migrations.AddField(
            model_name='efficiencyconfirmgroup',
            name='note',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='메모'),
        ),
        migrations.AddField(
            model_name='efficiencyconfirmgroup',
            name='title',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='그룹 제목'),
        ),
        migrations.AddIndex(
            model_name='efficiencychange',
            index=models.Index(fields=['confirm_group'], name='partner_eff_confirm_fb74e3_idx'),
        ),
    ]
