# Generated by Django 5.2.7 on 2026-01-03 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0019_efficiency_backfill_confirm_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='efficiencychange',
            name='confirm_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='efficiency_rows', to='partner.efficiencyconfirmgroup', verbose_name='확인서 그룹'),
        ),
    ]
